<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://schemas.nav.gov.hu/NTCA/1.0/receipt" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ntcaString="http://schemas.nav.gov.hu/NTCA/2.0/common/string" xmlns:ntcaCustomer="http://schemas.nav.gov.hu/NTCA/2.0/common/customer" xmlns:ntcaType="http://schemas.nav.gov.hu/NTCA/2.0/common/type" xmlns:ntcaAuth="http://schemas.nav.gov.hu/NTCA/2.0/common/authservice" xmlns:ntcaPaging="http://schemas.nav.gov.hu/NTCA/2.0/common/paging" xmlns:ntcaService="http://schemas.nav.gov.hu/NTCA/2.0/common/service" targetNamespace="http://schemas.nav.gov.hu/NTCA/1.0/receipt" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://schemas.nav.gov.hu/NTCA/2.0/common/string" schemaLocation="https://raw.githubusercontent.com/nav-gov-hu/Common/refs/tags/common-2.0.0-rc.2/schemas/src/main/resources/xsd/hu/gov/nav/schemas/NTCA/2.0/common/string.xsd"/>
	<xs:import namespace="http://schemas.nav.gov.hu/NTCA/2.0/common/customer" schemaLocation="https://raw.githubusercontent.com/nav-gov-hu/Common/refs/tags/common-2.0.0-rc.2/schemas/src/main/resources/xsd/hu/gov/nav/schemas/NTCA/2.0/common/customer.xsd"/>
	<xs:import namespace="http://schemas.nav.gov.hu/NTCA/2.0/common/type" schemaLocation="https://raw.githubusercontent.com/nav-gov-hu/Common/refs/tags/common-2.0.0-rc.2/schemas/src/main/resources/xsd/hu/gov/nav/schemas/NTCA/2.0/common/type.xsd"/>
	<xs:import namespace="http://schemas.nav.gov.hu/NTCA/2.0/common/authservice" schemaLocation="https://raw.githubusercontent.com/nav-gov-hu/Common/refs/tags/common-2.0.0-rc.2/schemas/src/main/resources/xsd/hu/gov/nav/schemas/NTCA/2.0/common/authservice.xsd"/>
	<xs:import namespace="http://schemas.nav.gov.hu/NTCA/2.0/common/paging" schemaLocation="https://raw.githubusercontent.com/nav-gov-hu/Common/refs/tags/common-2.0.0-rc.2/schemas/src/main/resources/xsd/hu/gov/nav/schemas/NTCA/2.0/common/paging.xsd"/>
	<xs:import namespace="http://schemas.nav.gov.hu/NTCA/2.0/common/service" schemaLocation="https://raw.githubusercontent.com/nav-gov-hu/Common/refs/tags/common-2.0.0-rc.2/schemas/src/main/resources/xsd/hu/gov/nav/schemas/NTCA/2.0/common/service.xsd"/>
	<xs:simpleType name="FixedDecimal112Type">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Fixpontos tizedes tört formátumú szám, amely maximális hosszúsági korlátokkal rendelkezik. Maximum 11 számjegy, beleértve 2 számjegyű tizedesjegyeket.</xs:documentation>
			<xs:documentation xml:lang="en">A fixed-point decimal number with strict length constraints. A maximum of 11 digits, including two decimal places.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-999999999.99"/>
			<xs:maxInclusive value="999999999.99"/>
			<xs:fractionDigits value="2"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="FixedDecimal212Type">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Fixpontos tizedes tört formátumú szám, amely maximális hosszúsági korlátokkal rendelkezik. Maximum 21 számjegy, beleértve 2 számjegyű tizedesjegyeket.</xs:documentation>
			<xs:documentation xml:lang="en">A fixed-point decimal number with strict length constraints. A maximum of 21 digits, including two decimal places.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-9999999999999999999.99"/>
			<xs:maxInclusive value="9999999999999999999.99"/>
			<xs:fractionDigits value="2"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PositiveFixedDecimal112Type">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Fixpontos pozitív tizedes tört formátumú szám, amely maximális hosszúsági korlátokkal rendelkezik. Maximum 11 számjegy, beleértve 2 számjegyű tizedesjegyeket.</xs:documentation>
			<xs:documentation xml:lang="en">A fixed-point positive decimal number with strict length constraints. A maximum of 11 digits, including two decimal places.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="FixedDecimal112Type">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ReceiptSerialNumberType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Kezdő nyugta sorszám formátumra való megszorítások</xs:documentation>
			<xs:documentation xml:lang="en">Restrictions on the format of the starting receipt number</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="50"/>
			<xs:pattern value="([A-Za-z0-9-])+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ExchangeRateType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Átváltási árfolyam értékére való megszorítások
      </xs:documentation>
			<xs:documentation xml:lang="en">Restrictions on the value of the exchange rate
      </xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="1000"/>
			<xs:totalDigits value="9"/>
			<xs:fractionDigits value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CountType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta darabszámok meghatározására használt típus</xs:documentation>
			<xs:documentation xml:lang="en">Type used to specify the number of items on a receipt</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="9999999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ReceiptListOrderingPropertyEnum">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta rendezésre használható értékek felsorolása
      </xs:documentation>
			<xs:documentation xml:lang="en">List of values that can be used for receipt ordering
      </xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="ID">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Egyedi azonosító</xs:documentation>
					<xs:documentation xml:lang="en">Unique identifier</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="APPLICABLE_DATE">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Tárgynap</xs:documentation>
					<xs:documentation xml:lang="en">Applicable date</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CREATED_DATE">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Létrehozás ideje</xs:documentation>
					<xs:documentation xml:lang="en">Created date</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="SERIAL_NUMBER">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Kezdő nyugta sorszáma</xs:documentation>
					<xs:documentation xml:lang="en">Serial number of the first receipt</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="NUM_SALE_DOC">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Kézi nyugtán bizonylatolt értékesítés darabszáma</xs:documentation>
					<xs:documentation xml:lang="en">Count of sale document</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="NUM_MODIFY_DOC">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Módosító, érvénytelenítő értékesítés darabszáma</xs:documentation>
					<xs:documentation xml:lang="en">Count of modifying or invalidating document</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="TOTAL">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Adatszolgáltatás végösszege</xs:documentation>
					<xs:documentation xml:lang="en">Total amount</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="TOTAL_IN_FT">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Végösszeg forintban</xs:documentation>
					<xs:documentation xml:lang="en">Total amount in forint</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="STATE">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Státusz</xs:documentation>
					<xs:documentation xml:lang="en">State</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="SOFTWARE">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Számlázó szoftver neve</xs:documentation>
					<xs:documentation xml:lang="en">Receipt issuing software</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ReceiptStatusEnum">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta státusz értékek felsorolása</xs:documentation>
			<xs:documentation xml:lang="en">Enumeration for receipt state</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="RECORDED"/>
			<xs:enumeration value="INVALIDATED"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ForintValueType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Típus a forint értékek leírására.</xs:documentation>
			<xs:documentation xml:lang="en">Type for HUF values.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IssuingSoftwareNameType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Számlázó szoftver nevéhez használt típus</xs:documentation>
			<xs:documentation xml:lang="en">Type used to specify an issuing software name</xs:documentation>
		</xs:annotation>
		<xs:restriction base="ntcaString:AtomicStringType100">
			<xs:pattern value="[A-ZÁÉÍÓÖŐÚÜŰa-záéíóöőúüű0-9.\s\-@+_]*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ReceiptIdentifierType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta adatrögzítés azonosítóhoz használt típus</xs:documentation>
			<xs:documentation xml:lang="en">Type used to specify a unique identifier of receipt</xs:documentation>
		</xs:annotation>
		<xs:restriction base="ntcaString:AtomicStringType50">
			<xs:pattern value="[0-9]{8}_[0-9]{8}_[0-9]+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="VatCategoryNameType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">ÁFA kategória névhez használt típus</xs:documentation>
			<xs:documentation xml:lang="en">Type used to specify an VAT category name</xs:documentation>
		</xs:annotation>
		<xs:restriction base="ntcaString:AtomicStringType50">
			<xs:pattern value="[A-Za-z0-9áéíóöőúüűÁÉÍÓÖŐÚÜŰ% ]*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="CurrencyType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Egy devizát leíró típus</xs:documentation>
			<xs:documentation xml:lang="en">A type that describes a currency</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="xs:string">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Deviza neve</xs:documentation>
					<xs:documentation xml:lang="en">Currency name</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="code" type="ntcaCustomer:CurrencyType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Deviza kód</xs:documentation>
					<xs:documentation xml:lang="en">Currency code</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="CurrencyRequest">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Regisztrált devizákat lekérdezéséhez használt típus
      </xs:documentation>
			<xs:documentation xml:lang="en">Type used to query registered currencies</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ntcaService:BaseRequestType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CurrenciesType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Devizákat tároló lista típus.</xs:documentation>
			<xs:documentation xml:lang="en">List type containing currencies.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="currency" type="CurrencyType" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Deviza lista</xs:documentation>
					<xs:documentation xml:lang="en">Currency list</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CurrencyResponseType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Regisztrált devizákat tartalmazó típus</xs:documentation>
			<xs:documentation xml:lang="en">Type containing registered currencies</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseResponseType">
				<xs:sequence>
					<xs:element name="currencies" type="CurrenciesType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Deviza lista</xs:documentation>
							<xs:documentation xml:lang="en">Currency list</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="CurrencyResponse">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Regisztrált devizákat tartalmazó válasz</xs:documentation>
			<xs:documentation xml:lang="en">Response containing registered currencies</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="CurrencyResponseType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="VatCategoryType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">ÁFA kategóriát leíró típus</xs:documentation>
			<xs:documentation xml:lang="en">VAT category type</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="VatCategoryNameType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">ÁFA kategória neve</xs:documentation>
					<xs:documentation xml:lang="en">Name of VAT category</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="validFrom" type="ntcaType:GenericDateType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Érvényesség kezdete</xs:documentation>
					<xs:documentation xml:lang="en">Valid from</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="validTo" type="ntcaType:GenericDateType" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Érvényesség vége</xs:documentation>
					<xs:documentation xml:lang="en">Valid to</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="VatCategoriesType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">ÁFA kategóriát tartalmazó lista típus</xs:documentation>
			<xs:documentation xml:lang="en">Type for VAT category containing list</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="category" type="VatCategoryType" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="hu">ÁFA kategóriát tartalmazó lista</xs:documentation>
					<xs:documentation xml:lang="en">VAT category containing list</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="VatCategoryRequest">
		<xs:annotation>
			<xs:documentation xml:lang="hu">ÁFA kategóriák lekérdezéséhez használt típus
      </xs:documentation>
			<xs:documentation xml:lang="en">Type used to query registered VAT categories
      </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ntcaService:BaseRequestType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="VatCategoryResponseType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">ÁFA kategóriákat tartalmazó típus</xs:documentation>
			<xs:documentation xml:lang="en">Type containing VAT categories</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseResponseType">
				<xs:sequence>
					<xs:element name="categories" type="VatCategoriesType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">ÁFA kategória neve</xs:documentation>
							<xs:documentation xml:lang="en">Name of VAT category</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="VatCategoryResponse">
		<xs:annotation>
			<xs:documentation xml:lang="hu">ÁFA kategóriákat tartalmazó válasz</xs:documentation>
			<xs:documentation xml:lang="en">Response containing VAT categories</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="VatCategoryResponseType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="IssuingSoftwareType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Számlázó szoftvert leíró típus</xs:documentation>
			<xs:documentation xml:lang="en">A type that describes a receipt issuing software
      </xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="IssuingSoftwareNameType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Számlázó szoftver neve</xs:documentation>
					<xs:documentation xml:lang="en">Name of the receipt issuing software</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CreateIssuingSoftwareRequestType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Új számlázó szoftver létrehozásához szükséges típus
      </xs:documentation>
			<xs:documentation xml:lang="en">Type required to create new receipt issuing software
      </xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseRequestType">
				<xs:sequence>
					<xs:element name="taxPayerId" type="ntcaCustomer:TaxpayerIdType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Az adószám nyolc jegyű törzsszám része</xs:documentation>
							<xs:documentation xml:lang="en">The 8-digit core number section of the tax number</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="name" type="IssuingSoftwareNameType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Számlázó szoftver neve</xs:documentation>
							<xs:documentation xml:lang="en">Name of the receipt issuing software</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="CreateIssuingSoftwareRequest">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Új számlázó szoftver létrehozásához használt kérés</xs:documentation>
			<xs:documentation xml:lang="en">Request for creating a new receipt issuing software</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="CreateIssuingSoftwareRequestType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="CreateIssuingSoftwareResponse">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Új számlázó szoftver létrehozásához küldött válasz
      </xs:documentation>
			<xs:documentation xml:lang="en">Response sent to create receipt issuing software
      </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ntcaService:BaseResponseType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="IssuingSoftwareListRequestType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Számlázó szoftverek lekérdezéséhez használt típus
      </xs:documentation>
			<xs:documentation xml:lang="en">Type used to query receipt issuing software</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseRequestType">
				<xs:sequence>
					<xs:element name="taxPayerId" type="ntcaCustomer:TaxpayerIdType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Az adószám nyolc jegyű törzsszám része</xs:documentation>
							<xs:documentation xml:lang="en">The 8-digit core number section of the tax number</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="IssuingSoftwareListRequest">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Számlázó szoftverek lekérdezéséhez használt kérés
      </xs:documentation>
			<xs:documentation xml:lang="en">Request used to query receipt issuing software</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="IssuingSoftwareListRequestType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="IssuingSoftwareTypeListType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Számlázó szoftverek tároló típus.</xs:documentation>
			<xs:documentation xml:lang="en">List type containing receipt issuing softwares.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="software" type="IssuingSoftwareType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Számlázó szoftver lista.</xs:documentation>
					<xs:documentation xml:lang="en">Receipt issuing software list.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="IssuingSoftwareListResponseType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Regisztrált számlázó szoftvereket tartalmazó típus
      </xs:documentation>
			<xs:documentation xml:lang="en">Type containing registered receipt issuing software
      </xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseResponseType">
				<xs:sequence>
					<xs:element name="issuingSoftwareList" type="IssuingSoftwareTypeListType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Regisztrált számlázó szoftvereket tartalmazó elem
              </xs:documentation>
							<xs:documentation xml:lang="en">Element containing registered receipt issuing software
              </xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="IssuingSoftwareListResponse">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Regisztrált számlázó szoftvereket tartalmazó válasz</xs:documentation>
			<xs:documentation xml:lang="en">Response containing registered receipt issuing software</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="IssuingSoftwareListResponseType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ReceiptVatCategoryRowType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Kézi nyugta bruttó összeértéke adott ÁFA csoporthoz
        tartozóan
      </xs:documentation>
			<xs:documentation xml:lang="en">Gross total amount of a receipt by VAT group
      </xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="vat" type="VatCategoryNameType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">ÁFA csoport neve</xs:documentation>
					<xs:documentation xml:lang="en">VAT group name</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="saleDocument" type="PositiveFixedDecimal112Type">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Kézi nyugtán bizonylatolt értékesítés</xs:documentation>
					<xs:documentation xml:lang="en">Sale documented on a manual receipt</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="modifyingDocument" type="FixedDecimal112Type">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Módosító, érvénytelenítő bizonylaton szereplő összegek
            összesen
          </xs:documentation>
					<xs:documentation xml:lang="en">Total of amounts on modifying, cancelling document
          </xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReceiptVatCategoriesType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">ÁFA csoportokat tároló típus.</xs:documentation>
			<xs:documentation xml:lang="en">List type contains VAT categories.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="vatCategory" type="ReceiptVatCategoryRowType" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="hu">ÁFA csoportok.</xs:documentation>
					<xs:documentation xml:lang="en">VAT categories.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CreateReceiptRequestType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Új nyugta adatrögzítéshez szükséges típus</xs:documentation>
			<xs:documentation xml:lang="en">Type for creating a new receipt</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseRequestType">
				<xs:sequence>
					<xs:element name="taxPayerId" type="ntcaCustomer:TaxpayerIdType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Az adószám nyolc jegyű törzsszám része</xs:documentation>
							<xs:documentation xml:lang="en">The 8-digit core number section of the tax number</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="issuingSoftware" type="IssuingSoftwareType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Nyugta kiállító szoftver</xs:documentation>
							<xs:documentation xml:lang="en">Receipt-issuing software</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="applicableDate" type="ntcaType:GenericDateType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Tárgynap, melyre az adatszolgáltatás történik
              </xs:documentation>
							<xs:documentation xml:lang="en">Applicable day for which the data are reported
              </xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="serialNumber" type="ReceiptSerialNumberType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Kezdő nyugta sorszám</xs:documentation>
							<xs:documentation xml:lang="en">Serial number of first receipt</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="currency" type="ntcaCustomer:CurrencyType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Az adatszolgáltatásban használt pénznem</xs:documentation>
							<xs:documentation xml:lang="en">Currency used in data reporting</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="exchangeRate" type="ExchangeRateType" nillable="true">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Átváltási árfolyam (1 egység)</xs:documentation>
							<xs:documentation xml:lang="en">Exchange rate (1 unit)</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="vatCategoryItems" type="ReceiptVatCategoriesType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Kézi nyugták BRUTTÓ összértéke</xs:documentation>
							<xs:documentation xml:lang="en">Total GROSS value of manual receipts</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="total" type="FixedDecimal212Type">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Adatszolgáltatás összesített bruttó értéke</xs:documentation>
							<xs:documentation xml:lang="en">Total amount of data provision</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="numberOfSaleDocument" type="CountType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Értékesítés bizonylatok darabszáma</xs:documentation>
							<xs:documentation xml:lang="en">Count of sale documents</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="numberOfModifyingDocument" type="CountType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Módosító, érvénytelenítő bizonylatok darabszáma
              </xs:documentation>
							<xs:documentation xml:lang="en">Count of modifying and invalidating documents
              </xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="CreateReceiptRequest">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Új nyugta adatrögzítéshez használt kérés</xs:documentation>
			<xs:documentation xml:lang="en">Request for creating a new receipt</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="CreateReceiptRequestType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CreateReceiptResponseType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Új nyugta adatrögzítésre adott válasz típus</xs:documentation>
			<xs:documentation xml:lang="en">Type used to modify an existing receipt</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseResponseType">
				<xs:sequence>
					<xs:element name="id" type="ReceiptIdentifierType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">A létrehozott nyugta-adatszolgáltatás egyedi azonosítója</xs:documentation>
							<xs:documentation xml:lang="en">The unique identifier of the created receipt data report</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="CreateReceiptResponse">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Új nyugta adatrögzítésre adott válasz</xs:documentation>
			<xs:documentation xml:lang="en">New receipt data entry response</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="CreateReceiptResponseType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ModifyReceiptRequestType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Meglévő nyugta módosításához használt típus</xs:documentation>
			<xs:documentation xml:lang="en">Type used to modify an existing receipt</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseRequestType">
				<xs:sequence>
					<xs:element name="id" type="ReceiptIdentifierType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Nyugta egyedi azonosítója</xs:documentation>
							<xs:documentation xml:lang="en">Unique identifier of receipt</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="taxPayerId" type="ntcaCustomer:TaxpayerIdType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Az adószám nyolc jegyű törzsszám része</xs:documentation>
							<xs:documentation xml:lang="en">The 8-digit core number section of the tax number</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="issuingSoftware" type="IssuingSoftwareType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Nyugta kiállító szoftver</xs:documentation>
							<xs:documentation xml:lang="en">Receipt-issuing software</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="applicableDate" type="ntcaType:GenericDateType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Tárgynap, melyre az adatszolgáltatás történik
              </xs:documentation>
							<xs:documentation xml:lang="en">Applicable day for which the data are reported
              </xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="currency" type="ntcaCustomer:CurrencyType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Az adatszolgáltatásban használt pénznem</xs:documentation>
							<xs:documentation xml:lang="en">Currency used in data reporting</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="exchangeRate" type="ExchangeRateType" nillable="true">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Átváltási árfolyam (1 egység)</xs:documentation>
							<xs:documentation xml:lang="en">Exchange rate (1 unit)</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="vatCategoryItems" type="ReceiptVatCategoriesType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Kézi nyugták BRUTTÓ összértéke</xs:documentation>
							<xs:documentation xml:lang="en">Total GROSS value of manual receipts</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="total" type="FixedDecimal212Type">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Adatszolgáltatás összesített bruttó értéke</xs:documentation>
							<xs:documentation xml:lang="en">Total amount of data provision</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="numberOfSaleDocument" type="CountType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Értékesítés bizonylatok darabszáma</xs:documentation>
							<xs:documentation xml:lang="en">Count of sale documents</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="numberOfModifyingDocument" type="CountType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Módosító, érvénytelenítő bizonylatok darabszáma
              </xs:documentation>
							<xs:documentation xml:lang="en">Count of modifying and invalidating documents
              </xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ModifyReceiptRequest">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Meglévő nyugta módosításához használt kérés</xs:documentation>
			<xs:documentation xml:lang="en">Request used to modify an existing receipt</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ModifyReceiptRequestType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ModifyReceiptResponseType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta adatrögzítés módosítására adott válasz típus
      </xs:documentation>
			<xs:documentation xml:lang="en">Modify receipt data entry response type</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseResponseType">
				<xs:sequence>
					<xs:element name="id" type="ReceiptIdentifierType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">A módosítás hatására létrehozott nyugta-adatszolgáltatás rekord egyedi azonosítója</xs:documentation>
							<xs:documentation xml:lang="en">The unique identifier of the receipt data report record created as a result of the modification</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ModifyReceiptResponse">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta adatrögzítés módosítására adott válasz
      </xs:documentation>
			<xs:documentation xml:lang="en">Modify receipt data entry response</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ModifyReceiptResponseType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="InvalidateReceiptRequestType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta adatrögzítés érvénytelenítéshez használt típus
      </xs:documentation>
			<xs:documentation xml:lang="en">Type of receipt used for invalidating</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseRequestType">
				<xs:sequence>
					<xs:element name="id" type="ReceiptIdentifierType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Nyugta egyedi azonosítója</xs:documentation>
							<xs:documentation xml:lang="en">Unique identifier of receipt</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="taxPayerId" type="ntcaCustomer:TaxpayerIdType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Az adószám nyolc jegyű törzsszám része</xs:documentation>
							<xs:documentation xml:lang="en">The 8-digit core number section of the tax number</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="InvalidateReceiptRequest">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta adatrögzítés érvénytelenítéshez használt kérés
      </xs:documentation>
			<xs:documentation xml:lang="en">Request of receipt used for invalidating</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="InvalidateReceiptRequestType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="InvalidateReceiptResponse">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta adatrögzítés érvénytelenítésre adott válasz
      </xs:documentation>
			<xs:documentation xml:lang="en">Invalidating receipt data entry response type
      </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ntcaService:BaseResponseType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ReceiptListOrderingType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta adatrögzítés listázás rendezési paramétereit tartalmazó típus
      </xs:documentation>
			<xs:documentation xml:lang="en">Type containing page ordering parameters for receipt data listing
      </xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="property" type="ReceiptListOrderingPropertyEnum">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Rendezési oszlop neve</xs:documentation>
					<xs:documentation xml:lang="en">Sort column name</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="direction" type="ntcaPaging:OrderByType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Sorrend (ASC, DESC)</xs:documentation>
					<xs:documentation xml:lang="en">Order (ASC, DESC)</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReceiptListRequestType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta adatrögzítések listázásához szükséges típus
      </xs:documentation>
			<xs:documentation xml:lang="en">Type used to listing receipts</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseRequestType">
				<xs:sequence>
					<xs:element name="paging" type="ntcaPaging:PaginationType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Lapozási paraméterek</xs:documentation>
							<xs:documentation xml:lang="en">Paging properties</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="ordering" type="ReceiptListOrderingType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Rendezési paraméterek</xs:documentation>
							<xs:documentation xml:lang="en">Ordering properties</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="taxPayerId" type="ntcaCustomer:TaxpayerIdType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Az adószám nyolc jegyű törzsszám része</xs:documentation>
							<xs:documentation xml:lang="en">The 8-digit core number section of the tax number</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="from" type="ntcaType:GenericDateType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Szűrési paraméter: nyugta kiállítási dátuma (mettől)
              </xs:documentation>
							<xs:documentation xml:lang="en">Filtering property: receipt issuing date (from)
              </xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="to" type="ntcaType:GenericDateType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Szűrési paraméter: nyugta kiállítási dátuma (meddig)
              </xs:documentation>
							<xs:documentation xml:lang="en">Filtering property: receipt issuing date (to)
              </xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ReceiptListRequest">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta adatrögzítések listázásához szükséges kérés
      </xs:documentation>
			<xs:documentation xml:lang="en">Request used to listing receipts</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ReceiptListRequestType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ReceiptListItemType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Egy nyugta általános leírását szolgáló típus
      </xs:documentation>
			<xs:documentation xml:lang="en">Type for a general description of a receipt</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="id" type="ReceiptIdentifierType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Nyugta egyedi azonosítója</xs:documentation>
					<xs:documentation xml:lang="en">Unique identifier of receipt</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="applicableDate" type="ntcaType:GenericDateType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Tárgynap, melyre az adatszolgáltatás történik
          </xs:documentation>
					<xs:documentation xml:lang="en">Applicable day for which the data are reported
          </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="serialNumber" type="ReceiptSerialNumberType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Kezdő nyugta sorszám</xs:documentation>
					<xs:documentation xml:lang="en">Serial number of first receipt</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="numberOfSaleDocument" type="CountType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Értékesítés bizonylatok darabszáma</xs:documentation>
					<xs:documentation xml:lang="en">Count of sale documents</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="numberOfModifyingDocument" type="CountType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Módosító, érvénytelenítő bizonylatok darabszáma
          </xs:documentation>
					<xs:documentation xml:lang="en">Count of modifying and invalidating documents
          </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="totalAmount" type="FixedDecimal212Type">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Adatszolgáltatás végösszege</xs:documentation>
					<xs:documentation xml:lang="en">Total amount of data provision</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="totalAmountInForint" type="ForintValueType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Végösszeg forintban</xs:documentation>
					<xs:documentation xml:lang="en">Total amount in forints</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="status" type="ReceiptStatusEnum">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Státusz</xs:documentation>
					<xs:documentation xml:lang="en">State</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="issuingSoftware" type="IssuingSoftwareType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Nyugta kiállító szoftver</xs:documentation>
					<xs:documentation xml:lang="en">Receipt-issuing software</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReceiptListItemsType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugtákat tároló típus.</xs:documentation>
			<xs:documentation xml:lang="en">List type containing receipts.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="receipt" type="ReceiptListItemType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Nyugták.</xs:documentation>
					<xs:documentation xml:lang="en">Receipts.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReceiptListResponseType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta adatrögzítések listázására adott válasz
      </xs:documentation>
			<xs:documentation xml:lang="en">Response to listing data entries for receipts
      </xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseResponseType">
				<xs:sequence>
					<xs:element name="paging" type="ntcaPaging:PaginationResponseType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Lapozási információk</xs:documentation>
							<xs:documentation xml:lang="en">Pagination information</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="result" type="ReceiptListItemsType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Nyugta lista</xs:documentation>
							<xs:documentation xml:lang="en">List of receipts</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ReceiptListResponse">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta adatrögzítések listázására adott válasz
      </xs:documentation>
			<xs:documentation xml:lang="en">Response to listing data entries for receipts
      </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ReceiptListResponseType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ReceiptDetailRequestType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta részletes adatainak lekérdezéséhez használt típus
      </xs:documentation>
			<xs:documentation xml:lang="en">Type used to retrieve detailed receipt information
      </xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseRequestType">
				<xs:sequence>
					<xs:element name="id" type="ReceiptIdentifierType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Nyugta egyedi azonosítója</xs:documentation>
							<xs:documentation xml:lang="en">Unique identifier of receipt</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="taxPayerId" type="ntcaCustomer:TaxpayerIdType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Az adószám nyolc jegyű törzsszám része</xs:documentation>
							<xs:documentation xml:lang="en">The 8-digit core number section of the tax number</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ReceiptDetailRequest">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta részletes adatainak lekérdezéséhez használt kérés
      </xs:documentation>
			<xs:documentation xml:lang="en">Request used to retrieve detailed receipt information
      </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ReceiptDetailRequestType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ReceiptDetailResponseType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta részletes adatait leíró típus</xs:documentation>
			<xs:documentation xml:lang="en">Type describing detailed receipt information
      </xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaService:BaseResponseType">
				<xs:sequence>
					<xs:element name="id" type="ReceiptIdentifierType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Nyugta egyedi azonosítója</xs:documentation>
							<xs:documentation xml:lang="en">Unique identifier of receipt</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="issuingSoftware" type="IssuingSoftwareType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Nyugta kiállító szoftver</xs:documentation>
							<xs:documentation xml:lang="en">Receipt-issuing software</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="applicableDate" type="ntcaType:GenericDateType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Tárgynap, melyre az adatszolgáltatás történik
              </xs:documentation>
							<xs:documentation xml:lang="en">Applicable day for which the data are reported
              </xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="status" type="ReceiptStatusEnum">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Státusz</xs:documentation>
							<xs:documentation xml:lang="en">Status</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="serialNumber" type="ReceiptSerialNumberType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Kezdő nyugta sorszám</xs:documentation>
							<xs:documentation xml:lang="en">Serial number of first receipt</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="currency" type="ntcaCustomer:CurrencyType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Az adatszolgáltatásban használt pénznem</xs:documentation>
							<xs:documentation xml:lang="en">Currency used in data reporting</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="exchangeRate" type="ExchangeRateType" nillable="true">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Átváltási árfolyam (1 egység)</xs:documentation>
							<xs:documentation xml:lang="en">Exchange rate (1 unit)</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="vatCategoryItems" type="ReceiptVatCategoriesType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Kézi nyugták BRUTTÓ összértéke</xs:documentation>
							<xs:documentation xml:lang="en">Total GROSS value of manual receipts</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="total" type="FixedDecimal212Type">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Adatszolgáltatás összesített bruttó értéke</xs:documentation>
							<xs:documentation xml:lang="en">Total amount of data provision</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="totalAmountInForint" type="ForintValueType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Végösszeg forintban</xs:documentation>
							<xs:documentation xml:lang="en">Total amount in forints</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="numberOfSaleDocument" type="CountType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Értékesítés bizonylatok darabszáma</xs:documentation>
							<xs:documentation xml:lang="en">Count of sale documents</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="numberOfModifyingDocument" type="CountType">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Módosító, érvénytelenítő bizonylatok darabszáma
              </xs:documentation>
							<xs:documentation xml:lang="en">Count of modifying and invalidating documents
              </xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ReceiptDetailResponse">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Nyugta részletes adatait leíró válasz</xs:documentation>
			<xs:documentation xml:lang="en">Response for detailed receipt information</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ReceiptDetailResponseType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="AuthTokenRequest">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Authentikációs kérés.</xs:documentation>
			<xs:documentation xml:lang="en">Authentication request.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ntcaAuth:LegacyAuthRequestType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="AuthTokenResponseType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Authentikációs válasz típus.</xs:documentation>
			<xs:documentation xml:lang="en">Authentication response type.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ntcaAuth:AuthResponseType">
				<xs:sequence>
					<xs:element name="token" type="ntcaString:AtomicStringType600" nillable="true">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Authentikációs token.</xs:documentation>
							<xs:documentation xml:lang="en">Authentication token.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="validTo" type="ntcaType:GenericTimestampMilliType" nillable="true">
						<xs:annotation>
							<xs:documentation xml:lang="hu">Token érvényességi ideje.</xs:documentation>
							<xs:documentation xml:lang="en">Token expiration time.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="AuthTokenResponse">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Authentikációs válasz.</xs:documentation>
			<xs:documentation xml:lang="en">Authentication response.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="AuthTokenResponseType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>
